use_frameworks!
platform :ios, '9.0'

target 'Web3_Tests' do
  pod 'Web3', :path => '../'
  pod 'Web3/PromiseKit', :path => '../'
  pod 'Web3/ContractABI', :path => '../'
  
  pod 'Quick', '~> 2.1.0'
  pod 'Nimble', '~> 8.0.0'
end
